<?php include 'header.php';?>

<section>
<header>
	<h1>Welcome Page</h1>
</header>

<div id="content">
	<h1>heading 1</h1>
	<h2>heading 2</h2>
	<h3>heading 3</h3>
	<h4>heading 4</h4>
	<h5>heading 5</h5>
	<h6>heading 6</h6>
	<p><a href="#">This is a link.</a></p>
	<p><strong>bold</strong> <em>italic</em></p>

	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin diam nibh, consequat sit amet augue a, dignissim finibus mi. Donec consequat, nisi non vehicula euismod, turpis arcu convallis arcu, id semper sapien nibh vel nisl. Cras cursus turpis ut aliquam feugiat. Maecenas finibus erat nec feugiat hendrerit. In quis turpis vel purus finibus eleifend ac aliquet nulla. Sed suscipit, ligula vel semper gravida, velit enim vulputate tortor, sed iaculis eros orci vitae nibh. Sed augue magna, gravida vitae egestas sit amet, gravida vitae lacus. Curabitur quis odio ipsum. Sed a enim nec orci egestas porta. Sed vel nunc volutpat nisi sodales cursus. Donec commodo, lacus ut mollis faucibus, enim eros ultrices augue, volutpat pellentesque tellus nisi ac justo. Aenean iaculis, dolor at efficitur malesuada, velit massa luctus sem, nec aliquam magna lacus eu sem. Pellentesque suscipit diam quis odio elementum, sed auctor dui fermentum. Vivamus ac neque sodales, suscipit mauris vel, faucibus mi. Aenean volutpat ipsum nec facilisis semper.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin diam nibh, consequat sit amet augue a, dignissim finibus mi. Donec consequat, nisi non vehicula euismod, turpis arcu convallis arcu, id semper sapien nibh vel nisl. Cras cursus turpis ut aliquam feugiat. Maecenas finibus erat nec feugiat hendrerit. In quis turpis vel purus finibus eleifend ac aliquet nulla. Sed suscipit, ligula vel semper gravida, velit enim vulputate tortor, sed iaculis eros orci vitae nibh. Sed augue magna, gravida vitae egestas sit amet, gravida vitae lacus. Curabitur quis odio ipsum. Sed a enim nec orci egestas porta. Sed vel nunc volutpat nisi sodales cursus. Donec commodo, lacus ut mollis faucibus, enim eros ultrices augue, volutpat pellentesque tellus nisi ac justo. Aenean iaculis, dolor at efficitur malesuada, velit massa luctus sem, nec aliquam magna lacus eu sem. Pellentesque suscipit diam quis odio elementum, sed auctor dui fermentum. Vivamus ac neque sodales, suscipit mauris vel, faucibus mi. Aenean volutpat ipsum nec facilisis semper.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin diam nibh, consequat sit amet augue a, dignissim finibus mi. Donec consequat, nisi non vehicula euismod, turpis arcu convallis arcu, id semper sapien nibh vel nisl. Cras cursus turpis ut aliquam feugiat. Maecenas finibus erat nec feugiat hendrerit. In quis turpis vel purus finibus eleifend ac aliquet nulla. Sed suscipit, ligula vel semper gravida, velit enim vulputate tortor, sed iaculis eros orci vitae nibh. Sed augue magna, gravida vitae egestas sit amet, gravida vitae lacus. Curabitur quis odio ipsum. Sed a enim nec orci egestas porta. Sed vel nunc volutpat nisi sodales cursus. Donec commodo, lacus ut mollis faucibus, enim eros ultrices augue, volutpat pellentesque tellus nisi ac justo. Aenean iaculis, dolor at efficitur malesuada, velit massa luctus sem, nec aliquam magna lacus eu sem. Pellentesque suscipit diam quis odio elementum, sed auctor dui fermentum. Vivamus ac neque sodales, suscipit mauris vel, faucibus mi. Aenean volutpat ipsum nec facilisis semper.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin diam nibh, consequat sit amet augue a, dignissim finibus mi. Donec consequat, nisi non vehicula euismod, turpis arcu convallis arcu, id semper sapien nibh vel nisl. Cras cursus turpis ut aliquam feugiat. Maecenas finibus erat nec feugiat hendrerit. In quis turpis vel purus finibus eleifend ac aliquet nulla. Sed suscipit, ligula vel semper gravida, velit enim vulputate tortor, sed iaculis eros orci vitae nibh. Sed augue magna, gravida vitae egestas sit amet, gravida vitae lacus. Curabitur quis odio ipsum. Sed a enim nec orci egestas porta. Sed vel nunc volutpat nisi sodales cursus. Donec commodo, lacus ut mollis faucibus, enim eros ultrices augue, volutpat pellentesque tellus nisi ac justo. Aenean iaculis, dolor at efficitur malesuada, velit massa luctus sem, nec aliquam magna lacus eu sem. Pellentesque suscipit diam quis odio elementum, sed auctor dui fermentum. Vivamus ac neque sodales, suscipit mauris vel, faucibus mi. Aenean volutpat ipsum nec facilisis semper.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin diam nibh, consequat sit amet augue a, dignissim finibus mi. Donec consequat, nisi non vehicula euismod, turpis arcu convallis arcu, id semper sapien nibh vel nisl. Cras cursus turpis ut aliquam feugiat. Maecenas finibus erat nec feugiat hendrerit. In quis turpis vel purus finibus eleifend ac aliquet nulla. Sed suscipit, ligula vel semper gravida, velit enim vulputate tortor, sed iaculis eros orci vitae nibh. Sed augue magna, gravida vitae egestas sit amet, gravida vitae lacus. Curabitur quis odio ipsum. Sed a enim nec orci egestas porta. Sed vel nunc volutpat nisi sodales cursus. Donec commodo, lacus ut mollis faucibus, enim eros ultrices augue, volutpat pellentesque tellus nisi ac justo. Aenean iaculis, dolor at efficitur malesuada, velit massa luctus sem, nec aliquam magna lacus eu sem. Pellentesque suscipit diam quis odio elementum, sed auctor dui fermentum. Vivamus ac neque sodales, suscipit mauris vel, faucibus mi. Aenean volutpat ipsum nec facilisis semper.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin diam nibh, consequat sit amet augue a, dignissim finibus mi. Donec consequat, nisi non vehicula euismod, turpis arcu convallis arcu, id semper sapien nibh vel nisl. Cras cursus turpis ut aliquam feugiat. Maecenas finibus erat nec feugiat hendrerit. In quis turpis vel purus finibus eleifend ac aliquet nulla. Sed suscipit, ligula vel semper gravida, velit enim vulputate tortor, sed iaculis eros orci vitae nibh. Sed augue magna, gravida vitae egestas sit amet, gravida vitae lacus. Curabitur quis odio ipsum. Sed a enim nec orci egestas porta. Sed vel nunc volutpat nisi sodales cursus. Donec commodo, lacus ut mollis faucibus, enim eros ultrices augue, volutpat pellentesque tellus nisi ac justo. Aenean iaculis, dolor at efficitur malesuada, velit massa luctus sem, nec aliquam magna lacus eu sem. Pellentesque suscipit diam quis odio elementum, sed auctor dui fermentum. Vivamus ac neque sodales, suscipit mauris vel, faucibus mi. Aenean volutpat ipsum nec facilisis semper.</p>
</div>

</section>

<?php include 'footer.php';?>